Be/feat/redis(#13)
softeerbootcamp-3rd/Team7-FiveGuys pull request #35
Opened 2024-02-09 20:38 UTC by eyeben

## ✏️ 작업 및 변경사항 설명
> EC2에서 redis를 설치한 후 연결 할 수 있도록 설정. Match 엔티티 생성 후 연동 확인
<br>

## 📝 작업 목록
- [ ] redis 연동
- [ ] redis 등록 및 조회 테스트
<br>

## ✅ 체크 리스트
- [ ] dev 브랜치에 pr을 날렸는가?
- [ ] 테스트 코드를 작성했는가?
- [ ] 리뷰어, 라벨, 프로젝트, 마일스톤을 추가하였는가?
<br>

## 참고사항

 - AWS에서 포트번호 6379 열었음
 - 보안을 위해 비밀번호 걸었음(슬랙 확인)

redis 연동 확인
![image](https://github.com/softeerbootcamp-3rd/Team7-FiveGuys/assets/62013201/f9f161d2-57b2-452f-8882-d4ceeb7723cf)

* resolve #13

2024-02-10 09:51 UTC, yo0919 requested changes
일단 좌표값만 위도,경도로 분리해주면 좋을것같아ㅛ

2024-02-10 09:51 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/entity/Match.java
> +    private String hostDestCoordinate;
string형으로 좌표를 관리한다는건 위도,경도를 합쳐서 하나의 string으로 관리한다는건가..? 뭔가 lattitude 랑 longtitude로 분리해야 좌표 찍기 편하지 않을까싶습니다. 예를들면 departlogtitude 와 departlattitude 이런식이요

2024-02-10 10:57 UTC, eyeben commented on BE/robocar/src/main/java/com/fiveguys/robocar/entity/Match.java
> +    private String hostDestCoordinate;
그게 좋아보이네요.
다른 엔티티들도  Coordinate로 되어 있어서 ERD 수정하고 한꺼번에 리펙토링 해야 할꺼 같아요.
리펙토링 이슈로 따로 빼서 진행 하겠습니다

2024-02-10 14:05 UTC, lsh2613 requested changes

2024-02-10 14:05 UTC, lsh2613 commented on BE/robocar/src/main/java/com/fiveguys/robocar/entity/Match.java
> +public class Match {
Match라는 클래스명이 다소 모호한감이 있는 것 같습니다.
CarpoolRequest로 바꾸는 건 어떨까요?

2024-02-10 14:06 UTC, lsh2613 commented on BE/robocar/src/main/java/com/fiveguys/robocar/entity/Match.java
> +    private String hostDestCoordinate;
좋은 의견이네요 👍🏼

2024-02-11 15:09 UTC, eyeben commented on BE/robocar/src/main/java/com/fiveguys/robocar/entity/Match.java
> +public class Match {
그렇네요 
바꾸고 커밋 했습니다

2024-02-12 06:28 UTC, lsh2613 approved these changes

2024-02-12 06:32 UTC, yo0919 approved these changes
수정하시느라 고생하셨습니다!

2024-02-12 07:57 UTC, merged