Be/feat/jwt(#14)
softeerbootcamp-3rd/Team7-FiveGuys pull request #51
Opened 2024-02-14 08:08 UTC by eyeben

## ✏️ 작업 및 변경사항 설명
접근 권한을 관리하기 위한 JWT 로직을 구현
<br>

## 📝 작업 목록
- [ ] JWT 발급
- [ ] JWT 유효성 검사
<br>

## ✅ 체크 리스트
- [ ] dev 브랜치에 pr을 날렸는가?
- [ ] 리뷰어를 추가하였는가?
<br>

## 참고사항
api 개발중 화이트리스트를 작성하여 토큰 검사 필터를 거치지 않는 로직을 추가 할 예정입니다.

2024-02-14 09:33 UTC, yo0919 requested changes
우선 키 부분부터 변경하면 좋을것같아요

2024-02-14 09:33 UTC, yo0919 commented on BE/robocar/src/test/java/com/fiveguys/robocar/config/FilterConfigTest.java
> +}
혹시 여기 filterconfig테스트 인건가요? jwtutil테스트 같기도하네요.

2024-02-14 09:33 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
> +    private static final String ISSUER = "FIVEGUYS";
아까 다같이 이야기한 깃허브 시크릿이랑 로컬에서 작업할때는 yml파일에 추가해서 하면 될것같긴하네요!

2024-02-14 09:41 UTC, lsh2613 requested changes

2024-02-14 09:41 UTC, lsh2613 commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
> +                .setSubject(loginId)
토큰을 만들 때 pk인 userId가 아닌 loginId를 한 이유가 있을까요?
나중에 해당 값에 대한 유효성을 검사할 때 User를 조회해야 할 텐데 pk 값으로 조회하는 것이 더 빠를 것 같습니다!

2024-02-14 09:41 UTC, lsh2613 commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
> +    //TODO
이 주석은 지워도 될 것 같아요!

2024-02-14 09:41 UTC, lsh2613 commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
> +    // Base64.getDecoder().decode(SECRET_KEY) -> SECRET_KEY.getBytes(StandardCharsets.UTF_8))
코드 설명이 아닌 안 쓰는 코드에 대한 주석도 지워야 할 것 같습니다

2024-02-14 09:41 UTC, lsh2613 commented on BE/robocar/src/test/java/com/fiveguys/robocar/config/FilterConfigTest.java
> +    Logger logger = LoggerFactory.getLogger("JWT Test");
@slf4j를 사용해 보는 건 어떨까요??

2024-02-14 16:12 UTC, eyeben commented
이전에 반복되는 생성을 방지하고자 JWT를 Static으로 하자는 이야기가 있었는데
구현중 문제가 생겨 공유드립니다

1. yml파일에서 **SECRET_KEY**의 값을 가져오기 위해서는 @Value 어노테이션을 사용해야 합니다.
2. static 필드값에 @Value 값을 넣을 수 없어서 아래와 같은 방법으로 해야합니다
https://www.baeldung.com/spring-inject-static-field
<br>
![image](https://github.com/softeerbootcamp-3rd/Team7-FiveGuys/assets/62013201/0fb49fcd-4553-4d26-8b3d-566ffed9df80)
3. 그러나 일부 메소드들도 static으로 선언되어 있고, 이들 또한  **SECRET_KEY**를 사용중이라 NullPointerException이 발생합니다.
![image](https://github.com/softeerbootcamp-3rd/Team7-FiveGuys/assets/62013201/25723ff9-9ee4-4c77-a566-93ca49a8b450)

2024-02-14 16:58 UTC, eyeben commented on BE/robocar/src/test/java/com/fiveguys/robocar/config/FilterConfigTest.java
> +}
jwtutil테스트가 맞습니다! 날카롭네요
수정했습니다

2024-02-14 17:01 UTC, eyeben commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
> +    // Base64.getDecoder().decode(SECRET_KEY) -> SECRET_KEY.getBytes(StandardCharsets.UTF_8))
그렇네요 주석이 너무 많으니 오히려 난잡해 보이네요
불필요해 보이는 주석들 전부 제거 했습니다!

2024-02-14 19:17 UTC, eyeben commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
> +    private static final String ISSUER = "FIVEGUYS";
반영 완료!
static에는 @Value를 사용할 수 없어서 해결하는데 생각보다 오래 걸렸네요 ㅠㅠ

2024-02-14 19:20 UTC, eyeben commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
> +                .setSubject(loginId)
미쳐 신경쓰지 못한 부분인데 중요한 내용이네요
수정했습니다!

2024-02-16 04:20 UTC, yo0919 approved these changes
제가 말씀드린 수정사항은 모두 수정된 것 같아요!

2024-02-18 06:29 UTC, lsh2613 approved these changes

2024-02-18 09:11 UTC, merged