[BE] Car Api 구현
softeerbootcamp-3rd/Team7-FiveGuys pull request #58
Opened 2024-02-15 08:25 UTC by yo0919

## ✏️ 작업 및 변경사항 설명
> Car Api 구현
<br>

## 📝 작업 목록
- [ ] CRUD
<br>

## ✅ 체크 리스트
- [ ] dev 브랜치에 pr을 날렸는가?
- [ ] 리뷰어를 추가하였는가?
<br>

## 참고사항
- 지도 api와 함께 사용해보기 위해 이전에 pr 날렸던 지도 api 구현 브랜치에 이어서 작성
- 수정이 putmapping 인지 patchmapping인지 확실히는 모르겠음
- 나머지 부분은 차고지 api와 같음

2024-02-18 07:02 UTC, lsh2613 requested changes

2024-02-18 07:02 UTC, lsh2613 commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JsonParserUtil.java
> +            double lng = coordinateArray.get(0).getAsDouble(); // JSON 배열에서 첫 번째 요소가 경도
코드의 주석을 달아서 설명하는 좋지만 coordinateArray.getLat() , getLng()라는 메소드를 만들어 주석을 생략할 수도 있겠네요

2024-02-18 07:02 UTC, lsh2613 commented on BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
> +        System.out.println("응답 JSON: " + jsonResponse);
로그를 사용하도록 리팩토링이 필요해보이네여

2024-02-18 07:02 UTC, lsh2613 commented on BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
> +        //String goal2 = "127.1156,37.3456";
필요없는 주석은 삭제 부탁드려요

2024-02-18 07:52 UTC, eyeben commented on BE/robocar/src/main/java/com/fiveguys/robocar/service/CarService.java
> +                .orElseThrow(() -> new EntityNotFoundException("Car not found with id: " + carId));
저는 orElse(null)로 했었는데 이렇게 쓰니 더 보기 좋네요
참고하겠습니다!

2024-02-18 08:09 UTC, eyeben requested changes

2024-02-18 08:09 UTC, eyeben commented on BE/robocar/src/test/java/com/fiveguys/robocar/service/RouteComparisonServiceTest.java
> +        System.out.println("테스트 성공: 최적 경로는 " + optimalRoute.getFirstDestination() + "에서 " + optimalRoute.getSecondDestination() + "으로 결정되었습니다.");
그 때 호눅스님께서 sout를 절대 남기지 말라고 하셨는데
궁금해서 찾아보니까 아래와 같네요

![image](https://github.com/softeerbootcamp-3rd/Team7-FiveGuys/assets/62013201/a1d10b91-0316-49e7-a561-ed7c05d2adba)

2024-02-18 10:49 UTC, yo0919 commented on BE/robocar/src/test/java/com/fiveguys/robocar/service/RouteComparisonServiceTest.java
> +        System.out.println("테스트 성공: 최적 경로는 " + optimalRoute.getFirstDestination() + "에서 " + optimalRoute.getSecondDestination() + "으로 결정되었습니다.");
엇 근데 이부분은 테스트코드라서 실제 프로덕션환경에서는 돌아가지 않는다고 판단했었는데 프로덕션환경이 아닌 테스트에서도 sout을 기피해야할까요? 본문에도 프로덕트의 코드에서 사용하면 안된다고 해서요

2024-02-19 02:36 UTC, yo0919 commented on BE/robocar/build.gradle
> +	implementation 'com.google.code.gson:gson:2.9.1'
수정했습니다!

2024-02-19 02:37 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/config/RestClientConfig.java
> +        return new RestTemplate();
좋습니다 :)

2024-02-19 02:37 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/service/CarService.java
> +        return carRepository.save(car); // 차량 정보 데이터베이스에 저장
오 이부분이 커밋이 안되어있었네요 바로 수정해서 올렸습니다

2024-02-19 02:37 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/service/MapService.java
> +
넵 분리했습니다~

2024-02-19 02:37 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/service/RouteComparisonService.java
> +    @Getter // Lombok 어노테이션을 사용하여 모든 필드의 getter 메서드를 자동 생성
수정했습니다~

2024-02-19 02:38 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/service/RouteService.java
> +    public static class RouteInfo {
좋은 생각인것같아요 일단 분리해두었습니다!

2024-02-19 02:39 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/util/JsonParserUtil.java
> +            double lng = coordinateArray.get(0).getAsDouble(); // JSON 배열에서 첫 번째 요소가 경도
이 부분은 lat,lng를 뽑아내기 위해 한번만 쓰는 부분인것같아서 일단 주석으로만 달아두겠습니다!

2024-02-19 02:39 UTC, yo0919 commented on BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
> +        System.out.println("응답 JSON: " + jsonResponse);
넵 일단 수정해뒀습니다!

2024-02-19 02:40 UTC, yo0919 commented on BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
> +        //String goal2 = "127.1156,37.3456";
good :)

2024-02-19 02:40 UTC, yo0919 commented on BE/robocar/src/main/java/com/fiveguys/robocar/service/CarService.java
> +                .orElseThrow(() -> new EntityNotFoundException("Car not found with id: " + carId));
감사합니다 :)

2024-02-19 06:07 UTC, eyeben commented on BE/robocar/src/test/java/com/fiveguys/robocar/service/RouteComparisonServiceTest.java
> +        System.out.println("테스트 성공: 최적 경로는 " + optimalRoute.getFirstDestination() + "에서 " + optimalRoute.getSecondDestination() + "으로 결정되었습니다.");
테스트에서는 적용이 안된다네요
신경쓰지 않아도 될 듯합니다!

2024-02-19 06:31 UTC, eyeben approved these changes
고생하셨습니다!

2024-02-19 06:31 UTC, yo0919 commented on BE/robocar/src/test/java/com/fiveguys/robocar/service/RouteComparisonServiceTest.java
> +        System.out.println("테스트 성공: 최적 경로는 " + optimalRoute.getFirstDestination() + "에서 " + optimalRoute.getSecondDestination() + "으로 결정되었습니다.");
넵 그래도 일단 모두 로그로 바꾸긴했습니다!

2024-02-19 08:02 UTC, lsh2613 approved these changes

2024-02-19 08:15 UTC, merged