[BE] NaverMap 한글주소를 좌표로 변환하는 로직추가
softeerbootcamp-3rd/Team7-FiveGuys pull request #79
Opened 2024-02-19 09:53 UTC by yo0919

## ✏️ 작업 및 변경사항 설명
> NaverMap 한글주소를 좌표로 변환하는 로직추가
<br>

## 📝 작업 목록
- [x] MapService와 JsonParserUtil에 한글주소를 좌표로 변환하는 로직 추가
- [x] NaverMapConfig를 사용해서 요청보내기로 구현
- [x] ResponseStatus에 좌표변환불가 메세지 추가
<br>

## ✅ 체크 리스트
- [ ] dev 브랜치에 pr을 날렸는가?
- [ ] 리뷰어를 추가하였는가?
<br>

## 참고사항
> 안드로이드에서 한글주소로 보내준다고해서 MapService에 지번,도로명주소등 상세 주소를 받으면 좌표로 변환하는 로직 추가하였습니다.

2024-02-19 15:25 UTC, lsh2613 requested changes

2024-02-19 15:25 UTC, lsh2613 commented on BE/robocar/src/main/java/com/fiveguys/robocar/config/NaverMapConfig.java
> +    public static final String GEOCODE_API_URL = "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode";
해당 부분에 대해 컨벤션을 정하지 않았지만 기본적으로 클래스 변수가 최상단으로 많이 둡니다! 해당 사항에 대해서도 컨벤션으로 관리하면 좋을 것 같네요~

2024-02-20 06:57 UTC, lsh2613 approved these changes

2024-02-20 07:06 UTC, eyeben approved these changes
요청드리려 했던 내용인데 벌써 해주셨네요
고생하셨습니다 👍

2024-02-20 07:13 UTC, merged